services:
  ftp-server:
    image: stilliard/pure-ftpd
    container_name: ftp-server
    networks:
      - inquisitor-network
    env_file:
      - .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./server:/home/user

  ftp-client:
    image: alpine
    container_name: ftp-client
    networks:
      - inquisitor-network
    env_file:
      - .env
    depends_on:
      - ftp-server
    volumes:
      - ./client:/client
    command: ["/bin/sh", "-c", "/client/ftp-upload.sh"]

  inquisitor:
    build: .
    container_name: inquisitor
    networks:
      - inquisitor-network
    privileged: true
    env_file:
      - .env
    depends_on:
      - ftp-client
      - ftp-server
    volumes:
      - ./inquisitor:/inquisitor

networks:
  inquisitor-network:
    driver: bridge
