
services:
  client:
    build: ./client
    container_name: client
    networks:
      - inqu_network
    tty: true
  server:
    build: ./server
    container_name: server
    ports:
      - "8021:21"
    networks:
      - inqu_network
    tty: true
  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      - inqu_network
    tty: true

networks:
  inqu_network:
    driver: bridge
